### ISSUE TITLE
Cannot read property 'toString' of null 

### ISSUE THREAD

**Issue by bluepapillon2** [codejie/js-call-r#1]
Tried to install and run the test, but get this error.   (Suspect it is an environment error rather than the code, but can't work out what!)

> node test/test.js

call R script to calc(Sync) "1 + 3 = "
D:\Dev\play\index.js:123
            error: result.stdout.toString()
                                 ^

TypeError: Cannot read property 'toString' of null
    at Object.callSync (D:\Dev\play\index.js:123:34)
    at Object.<anonymous> (D:\Dev\play\test\test.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! Test failed.  See above for more details.

**Comment by bluepapillon2** [comment]
Have now got it running on Linux - nice!. Two things the github instructions could make clear are
- how to make Rscript, the

**Comment by bluepapillon2** [comment]
Got it working on Linux - nice!   On Linux, the code finds Rscript.exe whereas can’t get this to work on windows.  (Even adding it to path.).  Also needed to install the R package jsonr.
